apiVersion: standard.oam.dev/v1alpha1
kind: Autoscaler
metadata:
  name: example-scaler
spec:
  minReplicas: 2                      # optional, Defaults: 1
  maxReplicas: 4                      # optional, cannot be less that minReplicas
  triggers:
    - name: weekend-cron
      enabled: true
      type: cron                      # cron scaler. It indicates the scaler is KEDA
      condition:
        startAt: "14:45"              # required. "HHMM"
        duration: 2h                 # required. start hour + duration < 24
        days: ["Monday", "Saturday"]  # optional. In which days the condition will take effect
        replicas: 4                   # optional.
        timezone: Asia/Shanghai       # optional. time zone
  targetWorkload:                     # set by users or be auto-patched by outsiders, like OAM
    name: "php-apache"
    apiVersion: "extensions/v1beta1"  # optional
    kind: "Deployment"                # optional

